services:
  portfolio-web:
    build: .
    image: vii4442/portofolio-web:${IMAGE_TAG:-latest}
    container_name: luthfie-portfolio
    restart: always
    networks:
      - web-network
    expose:
      - "80"

  portfolio-backend:
    build: ./backend
    image: vii4442/portofolio-backend:${IMAGE_TAG:-latest}
    container_name: portofolio-backend
    restart: always
    volumes:
      - ./backend:/app
      - uploads_data:/app/static/uploads
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - MONGO_DETAILS=${PROD_MONGO_DETAILS}
      - SECRET_KEY=${PROD_SECRET_KEY}
    networks:
      - web-network
    expose:
      - "8000"
    depends_on:
      - portfolio-mongodb

  portfolio-mongodb:
    image: mongo:latest
    container_name: portofolio-db
    restart: always
    volumes:
      - portfolio_mongodb_data:/data/db
    networks:
      - web-network
    expose:
      - "27017"

volumes:
  uploads_data:
  portfolio_mongodb_data:


networks:
  web-network:
    external: true
