services:
  portfolio-web:
    image: vii4442/portofolio-web:${IMAGE_TAG:-latest}
    container_name: luthfie-portfolio
    restart: always
    networks:
      - web-network
    expose:
      - "80"

networks:
  web-network:
    external: true
